# Generated by Django 4.2 on 2023-04-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(max_length=5, null=True, verbose_name='Звёзды'),
        ),
    ]
